---
- name: Setup | set kernel parameters
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: true
    sysctl_set: true
  become: true
  loop: "{{ sysctl_conf }}"
  notify:
    - systemctl restart service

- name: Setup | copy redis-disable-thp systemd service
  ansible.builtin.copy:
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  become: true
  loop: "{{ systemd_conf }}"
  notify:
    - systemctl restart service

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    backup: true
  loop: "{{ service_conf }}"
  become: true
  changed_when: true
  notify:
    - systemctl restart service

- name: Setup | create redisrc
  ansible.builtin.template:
    dest: "{{ ansible_env.HOME }}/.redisrc"
    src: "redisrc.j2"
    mode: "0600"

- name: Setup | add redisrc to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regex: "^source.*redisrc"
    line: source ~/.redisrc
    state: present
...
